update the files

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -55,3 +55,42 @@ jobs:
       run: |
         docker tag golang ${{ secrets.DOCKER_HUB_USERNAME }}/golang:latest
         docker push ${{ secrets.DOCKER_HUB_USERNAME }}/golang:latest
+  
+  deploy:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Deploy to EC2
+        uses: appleboy/ssh-action@v0.1.8
+        with:
+          host: ${{ secrets.EC2_HOST }}
+          username: ${{ secrets.EC2_USER }}
+          key: ${{ secrets.EC2_SSH_KEY }}
+          port: 22
+          script: |
+            # Ensure Docker is installed
+            if ! command -v docker &> /dev/null; then
+              echo "Docker not found, installing..."
+              sudo yum update -y
+              sudo yum install -y docker
+              sudo systemctl start docker
+              sudo systemctl enable docker
+              sudo usermod -aG docker aishwar
+            fi
+
+            # Pull Docker image and run container
+            echo "Pulling Docker image..."
+            sudo docker pull takkadapelly/golang
+
+            echo "Stopping and removing old container..."
+            sudo docker stop golang || true
+            sudo docker rm golang || true
+
+            echo "Running new container..."
+            sudo docker run -d -p 8083:8083 --name my-app takkadapelly/golang:latest
+          timeout: 30s
+          command_timeout: 10m
+          debug: false
+        
